name: functional_widget
description: A code generator that generates widget classes from their implementation as a function.
homepage: https://github.com/rrousselGit/functional_widget/tree/master/packages/functional_widget
version: 0.10.3

environment:
  sdk: '>=3.7.2 <4.0.0'

resolution: workspace

dependencies:
  analyzer:
  build:
  build_config:
  meta:
  functional_widget_annotation:
  source_gen:
  code_builder:
  collection:

dev_dependencies:
  test:
  dart_style:
  build_runner:
  code_gen_tester:
